### ISSUE TITLE
`prepareLocalStorage` never gets called

### ISSUE THREAD

**Issue by brycehanscomb** [3stacks/agander#3]
Here is line 21 of `page.js`:

    // Prepares the local storage
    require('./local-storage-prepare').prepareLocalStorage;

Is the reference to `prepareLocalStorage` supposed to be invoked here (`prepareLocalStorage()`)? Because right now it doesn't actually do anything.

**Comment by 3stacks** [comment]
Thank you, nice spot. Fixed it.

**Comment by 3stacks** [comment]
https://github.com/3stacks/agander/commit/73da4ade24fb630401555a9d5abfd2f7489a5fdb

**Comment by brycehanscomb** [comment]
👌🏿
