### ISSUE TITLE
Asana Task sort mode is clickable when not authorised

### ISSUE THREAD

**Issue by 3stacks** [3stacks/agander#39]

**Comment by 3stacks** [comment]
I can't replicate this, can you @brycehanscomb?

**Comment by brycehanscomb** [comment]
Looks ok to me?

What state are you actually describing as "Not Authorised"? Is it when no data has been entered or when the API returns an auth error or something else?

![screen shot 2016-03-22 at 6 00 02 pm](https://cloud.githubusercontent.com/assets/2107995/13944258/04416502-f058-11e5-835a-14169e493acc.png)

**Comment by 3stacks** [comment]
Error hasn't happened to me, but a Chris was looking at it in edit mode and he had the window pop up.
